spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db-aules.uji.es:5432/ei102725ecg
spring.datasource.username=tu_usuario_real
spring.datasource.password=tu_contraseña_real
spring.application.name=clubesportiu