spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbcUrl=jdbc:postgresql://92.186.175.90:5432/ei1027
spring.datasource.username=al417146
spring.datasource.password=5443417146

